[
  {
    "title" : "Mapbox",
    "description" : "1 month off the Monthly Standard Plan",
    "url" : "http://www.mapbox.com",
    "code" : "www.mapbox.com",
    "private" : true,
    "createdAt" : new Date("2014-09-15T11:48:07.271Z"),
    "city" : "grenoble",
    "userId" : Users.findOne({})._id,
  },
  {
    "city" : "lyon",
    "code" : "MAPBOX4DEVS",
    "createdAt" : new Date("2014-09-15T11:48:31.203Z"),
    "description" : "Mapbox is a one of the biggest providers of custom online maps for major websites such as Foursquare, Pinterest, Evernote, the Financial Times and Uber Technologies.",
    "hiddenIn" : [ ],
    "private" : false,
    "title" : "1 month standard plan",
    "updatedAt" : new Date("2014-09-15T11:52:09.077Z"),
    "url" : "http://Mapbox.com",
    "userId" : Users.findOne({})._id,
  },
  {
    "city" : "lyon",
    "code" : "https://teamtreehouse.com/subscribe/new?plan=5bdbbcd9",
    "createdAt" : new Date("2014-09-15T11:53:15.025Z"),
    "description" : "Treehouse is an online interactive education platform that offers courses in web, mobile and business development.",
    "private" : false,
    "title" : "-25% basic plan",
    "updatedAt" : new Date("2014-11-13T22:40:26.971Z"),
    "url" : "http://TeamTreehouse.com",
    "userId" : Users.findOne({})._id,
  },
  {
    "title" : "-75% for life on Individual plan",
    "description" : "collaborative screen sharing + multiple mouse cursors + voice chat",
    "url" : "http://screenhero.com",
    "code" : "9N30NLSWE3140",
    "private" : false,
    "createdAt" : new Date("2014-11-07T09:54:31.327Z"),
    "city" : "lyon",
    "userId" :  Users.findOne({})._id,
  },
  {
    "title" : "-20%",
    "description" : "Nomad cables",
    "url" : "http://hellonomad.com",
    "code" : "HCKRS",
    "private" : false,
    "createdAt" : new Date("2014-11-13T22:40:10.590Z"),
    "city" : "lyon",
    "userId" :  Users.findOne({})._id,
  },
  {
    "city" : "lyon",
    "code" : "LYONHCKR2D2",
    "createdAt" : new Date("2014-09-20T19:15:56.834Z"),
    "description" : "The Spark Core is an Ardruino compatible & Wi-Fi enabled development platform for creating connected devices",
    "private" : false,
    "title" : "-10%",
    "updatedAt" : new Date("2014-09-21T23:12:29.118Z"),
    "url" : "http://spark.io/",
    "userId" : Users.findOne({})._id,
  }

]