// Generated by CoffeeScript 1.6.3
(function() {
  $.fn.serializeObject = function(inclEmptyProps) {
    var a, o;
    o = {};
    a = this.serializeArray();
    $.each(a, function() {
      if (o[this.name] !== void 0) {
        if (!o[this.name].push) {
          o[this.name] = [o[this.name]];
        }
        return o[this.name].push(this.value || '');
      } else {
        return o[this.name] = this.value || '';
      }
    });
    if (!inclEmptyProps)
      _.each(o, function(v, k){ if(!v) delete o[k]; });
    return o;
  };

}).call(this);
