
// In this file we define database collections.
// The database that meteor is using have no scheme.
// We write down the structure of the collections in the comments below.


// Meteor.users is a collection that is already defined by meteor.
// We only specify an outline of the properties here.
/* 
  Meteor.users = new Meteor.Collection('users'); 
*/
/*
{
  _id: String,          // automatic generated by meteor
  createdAt: Date,      // automatic filled in by meteor

  profile: {            // user's public profile (visible for other users)
    picture: String,    // url of an avatar for this user
    name: String,       // full name of the user
    city: String,       // location/city    
    lang: String        // language e.a. 'en', 'nl' or 'fr'
    social: {
      facebook: String, // url to user's facebook profile
      github: String,   // url to user's github profile
      twitter: String   // url to user's twitter profile
    },
    skills: [ String ],           // array of skill name
    favoriteSkills: [ String ]    // skills that are also marked as favorite
  },

  services: {           // meteor stores login information here...
    resume: ...
    facebook: ...
    github: ...
    twitter: ...
  }
}
*/



// In the future we can define new collections below
// ....