
// In this file we define database collections.
// The database that meteor is using have no scheme.
// We write down the structure of the collections in the comments below.


// Meteor.users is a collection that is already defined by meteor.
// We only specify an outline of the properties here.
/* 
  Meteor.users = new Meteor.Collection('users'); 
*/
/*
{
  _id: String,          // automatic generated by meteor
  createdAt: Date,      // automatic filled in by meteor

  profile: {            // user's public profile (visible for other users)
    name: String,       // (optional) full name of the user
    birthdate: Date,    // (optional) date of birth
    avatar: String,     // (optional) url of an avatar for this user
    gender: String,     // (optional) male|female
    lang: String        // (optional) language e.a. 'en', 'nl' or 'fr'
    social: {
      facebook: String, // (optional) url to user's facebook profile
      github: String,   // (optional) url to user's github profile
      twitter: String   // (optional) url to user's twitter profile
    }
  },

  services: {           // meteor stores login information here...
    resume: ...
    facebook: ...
    github: ...
    twitter: ...
  }
}
*/


// In the future we can define new collections below
// ....